leebyron/spec-md

src/print.js
The using spec markdown docs, say we can call `html` like:
```
var fs = require('fs');
var specMarkdown = require('spec-md');
specMarkdown.html('./path/to/markdown.md').then(function (html) {
fs.writeFile('./path/to/output.html', html);
});
```
not passing in `_options`.
But if you don't pass in `_options` you will get:
```
Unhandled rejection TypeError: Cannot read property 'highlight' of undefined
```
This checks for the existence of `_options`.
=> Check for possible undefined options parameter

css/spec.css, spec/Markdown.md, src/grammar.pegjs, src/print.js
This introduces HTML block type which preserves formatting, including whitespace.
After some research, I found that different markdown parsers handle block HTML in different ways. This implementation is based on the original perl markdown parser which used perl's Text::Balanced parser. The parser will attempt to find the close tag of the original opening tag, but is sensitive to nested tags.
Fixes #5
=> Support HTML blocks

css/spec.css, src/print.js
This adds a sidebar showing the full TOC opened to the currently viewed section.
When there's not enough space to show a sidebar, it's collapsed under a toggle floating in the top corner.
Revisits @sevki's #2 
Fixes #3
=> Adds sidebar showing TOC

src/print.js, static/highlightName.js, static/spec.css
This guides the eye when following along with a complex algorithm or grammar to quickly spot other references to the same identifier.
=> Add highlights for unique names on hover.

spec/Usage.md, spec/metadata.json, src/print.js
This allows a new `head` option (via node API or within metadata.json) which provides the ability to insert any arbitrary string within the `<head>` tag of the output HTML.
This offers a way to add additional styles, scripts, and meta tags. As an example, you might use this feature to introduce KaTeX or MathJax.
Fixes #15
=> Add content to `<head>`

README.md
These don't work on the HTML rendered version. So one needs to add `sec-` in front it seems.
=> Fix the links to under sections.

README.md
Noticed these weren't working when checking out the spec, didn't see any other broken links.
=> Fix anchor tag section links in Getting Started

spec/Spec Additions.md, src/print.js, static/linkSelections.js, static/spec.css, test/readme/ast.json, test/readme/output.html, test/simple-header/output.html
This adds a feature to the built HTML file which allows any highlighted selection to be linked directly to with a hash link.
The selection is uniquely identified with a url-safe opaque identifier using `sel-` prefix to disambiguate.
=> Link to any highlighted section of a document.

static/linkSelections.js, static/spec.css, test/readme/output.html, test/simple-header/output.html
This adds a checksum to a selection link which is later checked to determine if a selection's content has changed since the link was originally created. If so, we display it differently to make it clear that the content may have changed to avoid confusion.
=> Checksum selection links

spec/Spec Additions.md, src/grammar.pegjs, test/readme/ast.json, test/readme/output.html
Based on proposal in #31
> Prettier likes to format embedded code blocks in our markdown. Generally, we like this too, except when we don't. Sometimes we deliberately want to format something "weird" to demonstrate that our language supports that; in those cases we don't want prettier to undo our "weird" formatting. To achieve this, we can use a raw codeblock
However the implementation differs by requiring a space before the language name (which still thwarts tools like GH and prettier) and makes this part of the parsed AST rather than part of the highlight function name.
=> Allow raw prefix on code block languages

spec/Markdown.md, src/grammar.pegjs, test/readme/ast.json, test/readme/output.html
Since GFM supports underscores for emphasis, we can do that here as well. Factored out of #31.
Note that this is breaking since previously if you have ambiguous underscores in open text that it may create a syntax error or italicize text. To correct this replace `_` with `\_`.
=> [Breaking] Support underscores for emphasis

README.md, package.json, spec/Spec Additions.md, src/grammar.pegjs, src/parse.js, test/readme/ast.json, test/readme/output.html
Supports use of standard markdown headers (`# Header`) as the title of a spec markdown document. Inspired by a similar change in #31 however this does not require wrapping the header in bold.
For some context, originally setext headers were required to differentiate between a document title and a section header in an imported file since spec-md did not differentiate between initial files and imported files. This change is possible by having pegjs support multiple starting positions for the parser and parse initial and imported documents differently.
This also allows us to remove the ast validation logic since that can now be encoded directly in the grammar.
=> Support standard markdown titles

src/grammar.pegjs, src/print.js, static/spec.css, test/duplicated-notes/output.html, test/graphql-spec/output.html, test/productions/output.html, test/readme/output.html, test/runner.js, test/sections/ast.json, test/sections/input.md, test/sections/output.html, test/tables/output.html, test/task-lists/output.html
Supports standard markdown headers up to H6 and uses the appropriate header tag (eg `#` to `h1`) in the rendered output. This is potentially breaking since previously `#` rendered a `h2`.
=> [Breaking] Support up to H6 sections

src/grammar.pegjs, src/print.js, test/escape-sequence/ast.json, test/escape-sequence/input.md, test/escape-sequence/output.html, test/graphql-spec/ast.json, test/readme/ast.json, test/runner.js, test/task-lists/ast.json
Inspired by #31, this moves markdown unencoding from the print step to the parse step, and in doing so applies it nearly everywhere that raw text is parsed, and no longer only `Text` nodes.
This means escape sequences can be found within names, grammar terminals, prose, string literals, and section headers.
=> Allow markdown escape sequences in more places

src/print.js, test/sections/ast.json, test/sections/imported.md, test/sections/input.md, test/sections/output.html
If a markdown link has a hash reference that resolves in the biblio, then link to where biblio wants to link. Also look for `sec-` and `()` variants to properly convert from links which would resolve when viewed in Github to links that would resolve within a printed spec md html file.
Fixes #32
=> Resolve link urls from biblio

spec/Spec Additions.md, src/grammar.pegjs, test/readme/ast.json, test/readme/output.html
To help resolve the issue raised in https://github.com/graphql/graphql-spec/pull/726, this allows each line of a grid of "one of" tokens to start with a line bullet.
The spec-md rendered results are equivalent, however in other tools the content should be much easier to read.
=> Allow bulleted lists in "one of" productions

src/grammar.pegjs
Prettier automatically escapes standalone `$`s, which comes out in spec text like:
```
\${intArg} typed as {Int} cannot be used as an argument to {booleanArg}, typed
as {Boolean}.
```
This PR correctly unescapes the `$` character so that the backslash is not output into the resulting HTML.
Relates to #31 (prettier support).
=> Unescape dollars in text

package.json, spec/Markdown.md, src/grammar.pegjs, test/escape-sequence/ast.json, test/escape-sequence/input.md, test/escape-sequence/output.html, test/readme/ast.json, test/readme/output.html
As I learned from #55, an extended set of punctuation from the original core set may be escaped. Commonmark defines all ascii punctuation as escapeable https://spec.commonmark.org/0.29/#backslash-escapes
This change extends the `escaped` grammar and `unescape()` function to include all ASCII punct ranges, and fixes some bugs uncovered by that change within quoted strings and grammar terminals.
A critical bug was another gap from commonmark for [code spans](https://spec.commonmark.org/0.29/#code-spans). This diff also includes multi backquote and space removal as defined. This removes a specmd-only quirk for quoted inline code as terminals.
=> Allow escaping any ASCII punctuation.

src/grammar.pegjs, test/escape-sequence/ast.json, test/escape-sequence/input.md, test/escape-sequence/output.html
Prettier will escape solitary `*`s; which means that for example the `Name` production in GraphQL becomes:
```
Name ::
- NameStart NameContinue\* [lookahead != NameContinue]
```
This fix ensures that the character is interpretted as it is intended.
Relates to #31 (prettier support). More PRs incoming.
=> Allow for escaped * in quantifiers

src/grammar.pegjs, test/productions/ast.json, test/productions/input.md, test/productions/output.html
Prettier adds newlines around bulleted lists, which for example means that the `ExecutableDirectiveLocation` production becomes:
```
ExecutableDirectiveLocation : one of
- `QUERY`
- `MUTATION`
- `SUBSCRIPTION`
- `FIELD`
- `FRAGMENT_DEFINITION`
- `FRAGMENT_SPREAD`
- `INLINE_FRAGMENT`
- `VARIABLE_DEFINITION`
```
This PR ensures that spec-md parses this as it is intended.
Relates to #31 (prettier support). Another PR incoming.
=> Allow newline after "one of"

src/grammar.pegjs, src/print.js, test/graphql-spec/ast.json, test/graphql-spec/output.html, test/readme/ast.json, test/readme/output.html, test/tables/ast.json, test/tables/output.html
This is not required for prettier support, but it does bring consistency to the printer. In Markdown you can write a table like:
```
a | b | c
--- | --- | ---
1 | 2 | 3
```
a | b | c
--- | --- | ---
1 | 2 | 3
or like:
```
| a   | b   | c   |
| --- | --- | --- |
| 1   | 2   | 3   |
```
| a   | b   | c   |
| --- | --- | --- |
| 1   | 2   | 3   |
The visual output of these is equivalent, but in spec-md the trailing spaces inside the `<th>` and `<td>` elements are included in the output HTML, leaving an output difference between the two forms.
Adopting this PR would cause whitespace-only churn now, but would lead to fewer table-related diffs in future.
=> Trim table cells

.github/workflows/test.yml, package.json, scripts/build.js, scripts/test.js, src/grammar.pegjs, src/parse.js, src/print.js
Adds Windows support by supporting CRLF line endings in the grammar and normalizing line endings during test runs.
Fixes #26
=> Add Windows support

scripts/test.js, spec/Spec Additions.md, src/grammar.pegjs, src/print.js, test/duplicated-notes/ast.json, test/graphql-spec/ast.json, test/graphql-spec/output.html, test/productions/ast.json, test/readme/ast.json, test/readme/output.html, test/sections/ast.json, test/simple-header/ast.json, test/smart-quotes/ast.json, test/smart-quotes/input.md, test/smart-quotes/output.html, test/tables/ast.json, test/task-lists/ast.json
Moves text formatting from the printer to the parser and fixes a few rendering bugs.
* Missing space before open single quote
* Replace pure-hyphens with ascii-hyphens
* Replaces cong with asymp
* Fix smart quotes following inline formatting
* Fix edge cases where arrows aren't rendered correctly
* Allow escaping smart typography
* Correctly escape ampersands
* Correctly escape quotes only within html attrs
* Correctly encode all URIs
Fixes #52
=> Overhaul smart typography

src/grammar.pegjs, src/print.js, test/graphql-spec/ast.json, test/graphql-spec/output.html, test/readme/ast.json, test/readme/output.html, test/tables/ast.json, test/tables/input.md, test/tables/output.html
While tables were supported, they were only supported in a limited sense. This improves the grammar to support the full GFM tables spec.
This is potentially breaking since it changes the AST shape and may cause rendering differences for existing tables
=> POTENTIALLY BREAKING: GFM Tables

src/visit.js
After adding `loc` non-enumerables, the previous object copying function is no longer sufficient. After any edits during `visit()` this information is lost.
=> FIX: visit should maintain location on edits

scripts/test.js, spec/Markdown.md, spec/Spec Additions.md, src/grammar.pegjs, test/headers/ast.json, test/headers/input.md, test/headers/output.html, test/readme-gh/ast.json, test/readme-gh/output.html, test/readme/ast.json, test/readme/output.html
This improves block and header parsing to allow nesting headers of arbitrary depth and centralizes the negative lookahead that breaks out new sections
=> Improve header parsing

src/grammar.pegjs
The `text` rule has some post processing that should be generalized to all variants. This factors that out to a shared function.
=> Generalize Text node construction

scripts/test.js, spec/Markdown.md, src/grammar.pegjs, src/print.js, test/graphql-spec/ast.json, test/links/ast.json, test/links/input.md, test/links/output.html, test/readme-gh/ast.json, test/readme-gh/output.html, test/readme/ast.json, test/readme/output.html, test/sections/ast.json, test/smart-quotes/ast.json, test/task-lists/ast.json, test/task-lists/input.md
Fix: Allows link urls to include encoded chars without double-encoding and supports markdown's balanced parens in urls.
Also restricts spaces in urls, adjust spacing rules around link parsing, and adds title support to links and images as per [commonmark](https://spec.commonmark.org/0.29/#links)
Fixes a small bug related to link restrictions in task lists
=> POTENTIALLY BREAKING: Update Links and Images to be closer to Commonmark spec

src/parse.js, test/sections/ast.json
Or at least, I _think_ this check is faulty.
This fix arose from debugging what was happening on a document with this structure:
```
Introduction
```
The output with this document was that the entire `sec2.md` AST was being inserted into the introduction.  This seemed to be because the root document's content array was never actually being flattened, so the array representing the `sec2.md` AST wasn't filtered out in the `content.type !== "Section"` check in `printIntro`.
I believe this also fixes #82.  I was able to reproduce the extraneous commas by importing a file that didn't start with a header.  In that case, the commas were the result of an array being stringified, which was only occurring because the array was never flattened.
=> Fix faulty key check in flattenDocuments
